LOCAL_PATH:= $(call my-dir)

include $(CLEAR_VARS)

LOCAL_MODULE:= lsqlite3

#LOCAL_MODULE_FILENAME := lsqlite3

LOCAL_SRC_FILES:= lsqlite3.c

DEPENDENT_LIB_PATH := $(LOCAL_PATH)/../../../dependent
GGE_LIB_PATH := $(LOCAL_PATH)/../../../source

LUA_PATH := $(GGE_LIB_PATH)/lua
SDL_PATH := $(DEPENDENT_LIB_PATH)/SDL
SQLITE3MC_PATH := $(DEPENDENT_LIB_PATH)/SQLite3MultipleCiphers/src

LOCAL_C_INCLUDES := $(SQLITE3MC_PATH)
LOCAL_C_INCLUDES += $(LUA_PATH)
LOCAL_C_INCLUDES += $(LOCAL_PATH)

LOCAL_SHARED_LIBRARIES := lua

LOCAL_STATIC_LIBRARIES := sqlite3mc

LOCAL_EXPORT_C_INCLUDES := $(LOCAL_C_INCLUDES)

include $(BUILD_SHARED_LIBRARY)