#include "lua_proxy.h"
#if defined(__ANDROID__) || defined(__APPLE__)
#include <dlfcn.h>
#include <stdio.h>
#if defined(__ANDROID__)
#include <android/log.h>
#define LOG_TAG "MYGXY_LUA_PROXY"
#define LOGE(...) __android_log_print(ANDROID_LOG_ERROR, LOG_TAG, __VA_ARGS__)
#else
#define LOGE(...) printf(__VA_ARGS__)
#endif

PFN_lua_newstate proxy_lua_newstate = NULL;
PFN_lua_close proxy_lua_close = NULL;
PFN_lua_newthread proxy_lua_newthread = NULL;
PFN_lua_resetthread proxy_lua_resetthread = NULL;
PFN_lua_atpanic proxy_lua_atpanic = NULL;
PFN_lua_version proxy_lua_version = NULL;
PFN_lua_absindex proxy_lua_absindex = NULL;
PFN_lua_gettop proxy_lua_gettop = NULL;
PFN_lua_settop proxy_lua_settop = NULL;
PFN_lua_pushvalue proxy_lua_pushvalue = NULL;
PFN_lua_rotate proxy_lua_rotate = NULL;
PFN_lua_copy proxy_lua_copy = NULL;
PFN_lua_checkstack proxy_lua_checkstack = NULL;
PFN_lua_xmove proxy_lua_xmove = NULL;
PFN_lua_isnumber proxy_lua_isnumber = NULL;
PFN_lua_isstring proxy_lua_isstring = NULL;
PFN_lua_iscfunction proxy_lua_iscfunction = NULL;
PFN_lua_isinteger proxy_lua_isinteger = NULL;
PFN_lua_isuserdata proxy_lua_isuserdata = NULL;
PFN_lua_type proxy_lua_type = NULL;
PFN_lua_typename proxy_lua_typename = NULL;
PFN_lua_tonumberx proxy_lua_tonumberx = NULL;
PFN_lua_tointegerx proxy_lua_tointegerx = NULL;
PFN_lua_toboolean proxy_lua_toboolean = NULL;
PFN_lua_tolstring proxy_lua_tolstring = NULL;
PFN_lua_rawlen proxy_lua_rawlen = NULL;
PFN_lua_tocfunction proxy_lua_tocfunction = NULL;
PFN_lua_touserdata proxy_lua_touserdata = NULL;
PFN_lua_tothread proxy_lua_tothread = NULL;
PFN_lua_topointer proxy_lua_topointer = NULL;
PFN_lua_arith proxy_lua_arith = NULL;
PFN_lua_rawequal proxy_lua_rawequal = NULL;
PFN_lua_compare proxy_lua_compare = NULL;
PFN_lua_pushnil proxy_lua_pushnil = NULL;
PFN_lua_pushnumber proxy_lua_pushnumber = NULL;
PFN_lua_pushinteger proxy_lua_pushinteger = NULL;
PFN_lua_pushlstring proxy_lua_pushlstring = NULL;
PFN_lua_pushstring proxy_lua_pushstring = NULL;
PFN_lua_pushvfstring proxy_lua_pushvfstring = NULL;
PFN_lua_pushfstring proxy_lua_pushfstring = NULL;
PFN_lua_pushcclosure proxy_lua_pushcclosure = NULL;
PFN_lua_pushboolean proxy_lua_pushboolean = NULL;
PFN_lua_pushlightuserdata proxy_lua_pushlightuserdata = NULL;
PFN_lua_pushthread proxy_lua_pushthread = NULL;
PFN_lua_getglobal proxy_lua_getglobal = NULL;
PFN_lua_gettable proxy_lua_gettable = NULL;
PFN_lua_getfield proxy_lua_getfield = NULL;
PFN_lua_geti proxy_lua_geti = NULL;
PFN_lua_rawget proxy_lua_rawget = NULL;
PFN_lua_rawgeti proxy_lua_rawgeti = NULL;
PFN_lua_rawgetp proxy_lua_rawgetp = NULL;
PFN_lua_createtable proxy_lua_createtable = NULL;
PFN_lua_newuserdatauv proxy_lua_newuserdatauv = NULL;
PFN_lua_getmetatable proxy_lua_getmetatable = NULL;
PFN_lua_getiuservalue proxy_lua_getiuservalue = NULL;
PFN_lua_setglobal proxy_lua_setglobal = NULL;
PFN_lua_settable proxy_lua_settable = NULL;
PFN_lua_setfield proxy_lua_setfield = NULL;
PFN_lua_seti proxy_lua_seti = NULL;
PFN_lua_rawset proxy_lua_rawset = NULL;
PFN_lua_rawseti proxy_lua_rawseti = NULL;
PFN_lua_rawsetp proxy_lua_rawsetp = NULL;
PFN_lua_setmetatable proxy_lua_setmetatable = NULL;
PFN_lua_setiuservalue proxy_lua_setiuservalue = NULL;
PFN_lua_callk proxy_lua_callk = NULL;
PFN_lua_pcallk proxy_lua_pcallk = NULL;
PFN_lua_load proxy_lua_load = NULL;
PFN_lua_dump proxy_lua_dump = NULL;
PFN_lua_yieldk proxy_lua_yieldk = NULL;
PFN_lua_resume proxy_lua_resume = NULL;
PFN_lua_status proxy_lua_status = NULL;
PFN_lua_isyieldable proxy_lua_isyieldable = NULL;
PFN_lua_setwarnf proxy_lua_setwarnf = NULL;
PFN_lua_warning proxy_lua_warning = NULL;
PFN_lua_gc proxy_lua_gc = NULL;
PFN_lua_error proxy_lua_error = NULL;
PFN_lua_next proxy_lua_next = NULL;
PFN_lua_concat proxy_lua_concat = NULL;
PFN_lua_len proxy_lua_len = NULL;
PFN_lua_stringtonumber proxy_lua_stringtonumber = NULL;
PFN_lua_getallocf proxy_lua_getallocf = NULL;
PFN_lua_setallocf proxy_lua_setallocf = NULL;
PFN_lua_toclose proxy_lua_toclose = NULL;
PFN_lua_closeslot proxy_lua_closeslot = NULL;
PFN_lua_getstack proxy_lua_getstack = NULL;
PFN_lua_getinfo proxy_lua_getinfo = NULL;
PFN_lua_getlocal proxy_lua_getlocal = NULL;
PFN_lua_setlocal proxy_lua_setlocal = NULL;
PFN_lua_getupvalue proxy_lua_getupvalue = NULL;
PFN_lua_setupvalue proxy_lua_setupvalue = NULL;
PFN_lua_upvalueid proxy_lua_upvalueid = NULL;
PFN_lua_upvaluejoin proxy_lua_upvaluejoin = NULL;
PFN_lua_sethook proxy_lua_sethook = NULL;
PFN_lua_gethook proxy_lua_gethook = NULL;
PFN_lua_gethookmask proxy_lua_gethookmask = NULL;
PFN_lua_gethookcount proxy_lua_gethookcount = NULL;
PFN_lua_setcstacklimit proxy_lua_setcstacklimit = NULL;
PFN_luaL_checkversion_ proxy_luaL_checkversion_ = NULL;
PFN_luaL_getmetafield proxy_luaL_getmetafield = NULL;
PFN_luaL_callmeta proxy_luaL_callmeta = NULL;
PFN_luaL_tolstring proxy_luaL_tolstring = NULL;
PFN_luaL_argerror proxy_luaL_argerror = NULL;
PFN_luaL_typeerror proxy_luaL_typeerror = NULL;
PFN_luaL_checklstring proxy_luaL_checklstring = NULL;
PFN_luaL_optlstring proxy_luaL_optlstring = NULL;
PFN_luaL_checknumber proxy_luaL_checknumber = NULL;
PFN_luaL_optnumber proxy_luaL_optnumber = NULL;
PFN_luaL_checkinteger proxy_luaL_checkinteger = NULL;
PFN_luaL_optinteger proxy_luaL_optinteger = NULL;
PFN_luaL_checkstack proxy_luaL_checkstack = NULL;
PFN_luaL_checktype proxy_luaL_checktype = NULL;
PFN_luaL_checkany proxy_luaL_checkany = NULL;
PFN_luaL_newmetatable proxy_luaL_newmetatable = NULL;
PFN_luaL_setmetatable proxy_luaL_setmetatable = NULL;
PFN_luaL_testudata proxy_luaL_testudata = NULL;
PFN_luaL_checkudata proxy_luaL_checkudata = NULL;
PFN_luaL_where proxy_luaL_where = NULL;
PFN_luaL_error proxy_luaL_error = NULL;
PFN_luaL_checkoption proxy_luaL_checkoption = NULL;
PFN_luaL_fileresult proxy_luaL_fileresult = NULL;
PFN_luaL_execresult proxy_luaL_execresult = NULL;
PFN_luaL_ref proxy_luaL_ref = NULL;
PFN_luaL_unref proxy_luaL_unref = NULL;
PFN_luaL_loadfilex proxy_luaL_loadfilex = NULL;
PFN_luaL_loadbufferx proxy_luaL_loadbufferx = NULL;
PFN_luaL_loadstring proxy_luaL_loadstring = NULL;
PFN_luaL_newstate proxy_luaL_newstate = NULL;
PFN_luaL_len proxy_luaL_len = NULL;
PFN_luaL_addgsub proxy_luaL_addgsub = NULL;
PFN_luaL_gsub proxy_luaL_gsub = NULL;
PFN_luaL_setfuncs proxy_luaL_setfuncs = NULL;
PFN_luaL_getsubtable proxy_luaL_getsubtable = NULL;
PFN_luaL_traceback proxy_luaL_traceback = NULL;
PFN_luaL_requiref proxy_luaL_requiref = NULL;
PFN_luaL_buffinit proxy_luaL_buffinit = NULL;
PFN_luaL_prepbuffsize proxy_luaL_prepbuffsize = NULL;
PFN_luaL_addlstring proxy_luaL_addlstring = NULL;
PFN_luaL_addstring proxy_luaL_addstring = NULL;
PFN_luaL_addvalue proxy_luaL_addvalue = NULL;
PFN_luaL_pushresult proxy_luaL_pushresult = NULL;
PFN_luaL_pushresultsize proxy_luaL_pushresultsize = NULL;
PFN_luaL_buffinitsize proxy_luaL_buffinitsize = NULL;

void init_lua_proxy(void) {
    // Search order for Lua symbols:
    // 1. RTLD_DEFAULT  - globally exported shared library symbols
    // 2. dlopen(NULL)  - entire process symbol space (finds statically linked Lua)
    // 3. Platform-specific library names (Android .so / iOS .framework)
    void* handle = RTLD_DEFAULT;
    void* self_handle = dlopen(NULL, RTLD_LAZY); // process-wide symbol table
    
    void* gge_handle = NULL;
    void* lua_handle = NULL;
#if defined(__ANDROID__)
    gge_handle = dlopen("libggelua.so", RTLD_LAZY | RTLD_GLOBAL);
    lua_handle = dlopen("liblua54.so", RTLD_LAZY | RTLD_GLOBAL);
#elif defined(__APPLE__)
    // iOS: try framework paths, then RTLD_MAIN_ONLY for statically linked symbols
    gge_handle = dlopen("libggelua.framework/libggelua", RTLD_LAZY | RTLD_GLOBAL);
    if (!gge_handle) gge_handle = dlopen("libggelua", RTLD_LAZY | RTLD_GLOBAL);
    if (!gge_handle) gge_handle = RTLD_MAIN_ONLY;
    lua_handle = dlopen("liblua54.framework/liblua54", RTLD_LAZY | RTLD_GLOBAL);
    if (!lua_handle) lua_handle = dlopen("liblua54", RTLD_LAZY | RTLD_GLOBAL);
#endif
    
    // Macro for 4-level symbol lookup: RTLD_DEFAULT -> dlopen(NULL) -> engine lib -> lua lib
    #define RESOLVE_LUA(name, type) \
        proxy_##name = (type)dlsym(handle, #name); \
        if (!proxy_##name && self_handle) proxy_##name = (type)dlsym(self_handle, #name); \
        if (!proxy_##name && gge_handle) proxy_##name = (type)dlsym(gge_handle, #name); \
        if (!proxy_##name && lua_handle) proxy_##name = (type)dlsym(lua_handle, #name); \
        if (!proxy_##name) LOGE("Failed to resolve Lua symbol: " #name "\n");

    RESOLVE_LUA(lua_newstate, PFN_lua_newstate);
    proxy_lua_close = (PFN_lua_close)dlsym(handle, "lua_close");
    if (!proxy_lua_close && gge_handle) proxy_lua_close = (PFN_lua_close)dlsym(gge_handle, "lua_close");
    if (!proxy_lua_close && lua_handle) proxy_lua_close = (PFN_lua_close)dlsym(lua_handle, "lua_close");
    if (!proxy_lua_close) LOGE("Failed to resolve Lua symbol: lua_close\n");
    proxy_lua_newthread = (PFN_lua_newthread)dlsym(handle, "lua_newthread");
    if (!proxy_lua_newthread && gge_handle) proxy_lua_newthread = (PFN_lua_newthread)dlsym(gge_handle, "lua_newthread");
    if (!proxy_lua_newthread && lua_handle) proxy_lua_newthread = (PFN_lua_newthread)dlsym(lua_handle, "lua_newthread");
    if (!proxy_lua_newthread) LOGE("Failed to resolve Lua symbol: lua_newthread\n");
    proxy_lua_resetthread = (PFN_lua_resetthread)dlsym(handle, "lua_resetthread");
    if (!proxy_lua_resetthread && gge_handle) proxy_lua_resetthread = (PFN_lua_resetthread)dlsym(gge_handle, "lua_resetthread");
    if (!proxy_lua_resetthread && lua_handle) proxy_lua_resetthread = (PFN_lua_resetthread)dlsym(lua_handle, "lua_resetthread");
    if (!proxy_lua_resetthread) LOGE("Failed to resolve Lua symbol: lua_resetthread\n");
    proxy_lua_atpanic = (PFN_lua_atpanic)dlsym(handle, "lua_atpanic");
    if (!proxy_lua_atpanic && gge_handle) proxy_lua_atpanic = (PFN_lua_atpanic)dlsym(gge_handle, "lua_atpanic");
    if (!proxy_lua_atpanic && lua_handle) proxy_lua_atpanic = (PFN_lua_atpanic)dlsym(lua_handle, "lua_atpanic");
    if (!proxy_lua_atpanic) LOGE("Failed to resolve Lua symbol: lua_atpanic\n");
    proxy_lua_version = (PFN_lua_version)dlsym(handle, "lua_version");
    if (!proxy_lua_version && gge_handle) proxy_lua_version = (PFN_lua_version)dlsym(gge_handle, "lua_version");
    if (!proxy_lua_version && lua_handle) proxy_lua_version = (PFN_lua_version)dlsym(lua_handle, "lua_version");
    if (!proxy_lua_version) LOGE("Failed to resolve Lua symbol: lua_version\n");
    proxy_lua_absindex = (PFN_lua_absindex)dlsym(handle, "lua_absindex");
    if (!proxy_lua_absindex && gge_handle) proxy_lua_absindex = (PFN_lua_absindex)dlsym(gge_handle, "lua_absindex");
    if (!proxy_lua_absindex && lua_handle) proxy_lua_absindex = (PFN_lua_absindex)dlsym(lua_handle, "lua_absindex");
    if (!proxy_lua_absindex) LOGE("Failed to resolve Lua symbol: lua_absindex\n");
    proxy_lua_gettop = (PFN_lua_gettop)dlsym(handle, "lua_gettop");
    if (!proxy_lua_gettop && gge_handle) proxy_lua_gettop = (PFN_lua_gettop)dlsym(gge_handle, "lua_gettop");
    if (!proxy_lua_gettop && lua_handle) proxy_lua_gettop = (PFN_lua_gettop)dlsym(lua_handle, "lua_gettop");
    if (!proxy_lua_gettop) LOGE("Failed to resolve Lua symbol: lua_gettop\n");
    proxy_lua_settop = (PFN_lua_settop)dlsym(handle, "lua_settop");
    if (!proxy_lua_settop && gge_handle) proxy_lua_settop = (PFN_lua_settop)dlsym(gge_handle, "lua_settop");
    if (!proxy_lua_settop && lua_handle) proxy_lua_settop = (PFN_lua_settop)dlsym(lua_handle, "lua_settop");
    if (!proxy_lua_settop) LOGE("Failed to resolve Lua symbol: lua_settop\n");
    proxy_lua_pushvalue = (PFN_lua_pushvalue)dlsym(handle, "lua_pushvalue");
    if (!proxy_lua_pushvalue && gge_handle) proxy_lua_pushvalue = (PFN_lua_pushvalue)dlsym(gge_handle, "lua_pushvalue");
    if (!proxy_lua_pushvalue && lua_handle) proxy_lua_pushvalue = (PFN_lua_pushvalue)dlsym(lua_handle, "lua_pushvalue");
    if (!proxy_lua_pushvalue) LOGE("Failed to resolve Lua symbol: lua_pushvalue\n");
    proxy_lua_rotate = (PFN_lua_rotate)dlsym(handle, "lua_rotate");
    if (!proxy_lua_rotate && gge_handle) proxy_lua_rotate = (PFN_lua_rotate)dlsym(gge_handle, "lua_rotate");
    if (!proxy_lua_rotate && lua_handle) proxy_lua_rotate = (PFN_lua_rotate)dlsym(lua_handle, "lua_rotate");
    if (!proxy_lua_rotate) LOGE("Failed to resolve Lua symbol: lua_rotate\n");
    proxy_lua_copy = (PFN_lua_copy)dlsym(handle, "lua_copy");
    if (!proxy_lua_copy && gge_handle) proxy_lua_copy = (PFN_lua_copy)dlsym(gge_handle, "lua_copy");
    if (!proxy_lua_copy && lua_handle) proxy_lua_copy = (PFN_lua_copy)dlsym(lua_handle, "lua_copy");
    if (!proxy_lua_copy) LOGE("Failed to resolve Lua symbol: lua_copy\n");
    proxy_lua_checkstack = (PFN_lua_checkstack)dlsym(handle, "lua_checkstack");
    if (!proxy_lua_checkstack && gge_handle) proxy_lua_checkstack = (PFN_lua_checkstack)dlsym(gge_handle, "lua_checkstack");
    if (!proxy_lua_checkstack && lua_handle) proxy_lua_checkstack = (PFN_lua_checkstack)dlsym(lua_handle, "lua_checkstack");
    if (!proxy_lua_checkstack) LOGE("Failed to resolve Lua symbol: lua_checkstack\n");
    proxy_lua_xmove = (PFN_lua_xmove)dlsym(handle, "lua_xmove");
    if (!proxy_lua_xmove && gge_handle) proxy_lua_xmove = (PFN_lua_xmove)dlsym(gge_handle, "lua_xmove");
    if (!proxy_lua_xmove && lua_handle) proxy_lua_xmove = (PFN_lua_xmove)dlsym(lua_handle, "lua_xmove");
    if (!proxy_lua_xmove) LOGE("Failed to resolve Lua symbol: lua_xmove\n");
    proxy_lua_isnumber = (PFN_lua_isnumber)dlsym(handle, "lua_isnumber");
    if (!proxy_lua_isnumber && gge_handle) proxy_lua_isnumber = (PFN_lua_isnumber)dlsym(gge_handle, "lua_isnumber");
    if (!proxy_lua_isnumber && lua_handle) proxy_lua_isnumber = (PFN_lua_isnumber)dlsym(lua_handle, "lua_isnumber");
    if (!proxy_lua_isnumber) LOGE("Failed to resolve Lua symbol: lua_isnumber\n");
    proxy_lua_isstring = (PFN_lua_isstring)dlsym(handle, "lua_isstring");
    if (!proxy_lua_isstring && gge_handle) proxy_lua_isstring = (PFN_lua_isstring)dlsym(gge_handle, "lua_isstring");
    if (!proxy_lua_isstring && lua_handle) proxy_lua_isstring = (PFN_lua_isstring)dlsym(lua_handle, "lua_isstring");
    if (!proxy_lua_isstring) LOGE("Failed to resolve Lua symbol: lua_isstring\n");
    proxy_lua_iscfunction = (PFN_lua_iscfunction)dlsym(handle, "lua_iscfunction");
    if (!proxy_lua_iscfunction && gge_handle) proxy_lua_iscfunction = (PFN_lua_iscfunction)dlsym(gge_handle, "lua_iscfunction");
    if (!proxy_lua_iscfunction && lua_handle) proxy_lua_iscfunction = (PFN_lua_iscfunction)dlsym(lua_handle, "lua_iscfunction");
    if (!proxy_lua_iscfunction) LOGE("Failed to resolve Lua symbol: lua_iscfunction\n");
    proxy_lua_isinteger = (PFN_lua_isinteger)dlsym(handle, "lua_isinteger");
    if (!proxy_lua_isinteger && gge_handle) proxy_lua_isinteger = (PFN_lua_isinteger)dlsym(gge_handle, "lua_isinteger");
    if (!proxy_lua_isinteger && lua_handle) proxy_lua_isinteger = (PFN_lua_isinteger)dlsym(lua_handle, "lua_isinteger");
    if (!proxy_lua_isinteger) LOGE("Failed to resolve Lua symbol: lua_isinteger\n");
    proxy_lua_isuserdata = (PFN_lua_isuserdata)dlsym(handle, "lua_isuserdata");
    if (!proxy_lua_isuserdata && gge_handle) proxy_lua_isuserdata = (PFN_lua_isuserdata)dlsym(gge_handle, "lua_isuserdata");
    if (!proxy_lua_isuserdata && lua_handle) proxy_lua_isuserdata = (PFN_lua_isuserdata)dlsym(lua_handle, "lua_isuserdata");
    if (!proxy_lua_isuserdata) LOGE("Failed to resolve Lua symbol: lua_isuserdata\n");
    proxy_lua_type = (PFN_lua_type)dlsym(handle, "lua_type");
    if (!proxy_lua_type && gge_handle) proxy_lua_type = (PFN_lua_type)dlsym(gge_handle, "lua_type");
    if (!proxy_lua_type && lua_handle) proxy_lua_type = (PFN_lua_type)dlsym(lua_handle, "lua_type");
    if (!proxy_lua_type) LOGE("Failed to resolve Lua symbol: lua_type\n");
    proxy_lua_typename = (PFN_lua_typename)dlsym(handle, "lua_typename");
    if (!proxy_lua_typename && gge_handle) proxy_lua_typename = (PFN_lua_typename)dlsym(gge_handle, "lua_typename");
    if (!proxy_lua_typename && lua_handle) proxy_lua_typename = (PFN_lua_typename)dlsym(lua_handle, "lua_typename");
    if (!proxy_lua_typename) LOGE("Failed to resolve Lua symbol: lua_typename\n");
    proxy_lua_tonumberx = (PFN_lua_tonumberx)dlsym(handle, "lua_tonumberx");
    if (!proxy_lua_tonumberx && gge_handle) proxy_lua_tonumberx = (PFN_lua_tonumberx)dlsym(gge_handle, "lua_tonumberx");
    if (!proxy_lua_tonumberx && lua_handle) proxy_lua_tonumberx = (PFN_lua_tonumberx)dlsym(lua_handle, "lua_tonumberx");
    if (!proxy_lua_tonumberx) LOGE("Failed to resolve Lua symbol: lua_tonumberx\n");
    proxy_lua_tointegerx = (PFN_lua_tointegerx)dlsym(handle, "lua_tointegerx");
    if (!proxy_lua_tointegerx && gge_handle) proxy_lua_tointegerx = (PFN_lua_tointegerx)dlsym(gge_handle, "lua_tointegerx");
    if (!proxy_lua_tointegerx && lua_handle) proxy_lua_tointegerx = (PFN_lua_tointegerx)dlsym(lua_handle, "lua_tointegerx");
    if (!proxy_lua_tointegerx) LOGE("Failed to resolve Lua symbol: lua_tointegerx\n");
    proxy_lua_toboolean = (PFN_lua_toboolean)dlsym(handle, "lua_toboolean");
    if (!proxy_lua_toboolean && gge_handle) proxy_lua_toboolean = (PFN_lua_toboolean)dlsym(gge_handle, "lua_toboolean");
    if (!proxy_lua_toboolean && lua_handle) proxy_lua_toboolean = (PFN_lua_toboolean)dlsym(lua_handle, "lua_toboolean");
    if (!proxy_lua_toboolean) LOGE("Failed to resolve Lua symbol: lua_toboolean\n");
    proxy_lua_tolstring = (PFN_lua_tolstring)dlsym(handle, "lua_tolstring");
    if (!proxy_lua_tolstring && gge_handle) proxy_lua_tolstring = (PFN_lua_tolstring)dlsym(gge_handle, "lua_tolstring");
    if (!proxy_lua_tolstring && lua_handle) proxy_lua_tolstring = (PFN_lua_tolstring)dlsym(lua_handle, "lua_tolstring");
    if (!proxy_lua_tolstring) LOGE("Failed to resolve Lua symbol: lua_tolstring\n");
    proxy_lua_rawlen = (PFN_lua_rawlen)dlsym(handle, "lua_rawlen");
    if (!proxy_lua_rawlen && gge_handle) proxy_lua_rawlen = (PFN_lua_rawlen)dlsym(gge_handle, "lua_rawlen");
    if (!proxy_lua_rawlen && lua_handle) proxy_lua_rawlen = (PFN_lua_rawlen)dlsym(lua_handle, "lua_rawlen");
    if (!proxy_lua_rawlen) LOGE("Failed to resolve Lua symbol: lua_rawlen\n");
    proxy_lua_tocfunction = (PFN_lua_tocfunction)dlsym(handle, "lua_tocfunction");
    if (!proxy_lua_tocfunction && gge_handle) proxy_lua_tocfunction = (PFN_lua_tocfunction)dlsym(gge_handle, "lua_tocfunction");
    if (!proxy_lua_tocfunction && lua_handle) proxy_lua_tocfunction = (PFN_lua_tocfunction)dlsym(lua_handle, "lua_tocfunction");
    if (!proxy_lua_tocfunction) LOGE("Failed to resolve Lua symbol: lua_tocfunction\n");
    proxy_lua_touserdata = (PFN_lua_touserdata)dlsym(handle, "lua_touserdata");
    if (!proxy_lua_touserdata && gge_handle) proxy_lua_touserdata = (PFN_lua_touserdata)dlsym(gge_handle, "lua_touserdata");
    if (!proxy_lua_touserdata && lua_handle) proxy_lua_touserdata = (PFN_lua_touserdata)dlsym(lua_handle, "lua_touserdata");
    if (!proxy_lua_touserdata) LOGE("Failed to resolve Lua symbol: lua_touserdata\n");
    proxy_lua_tothread = (PFN_lua_tothread)dlsym(handle, "lua_tothread");
    if (!proxy_lua_tothread && gge_handle) proxy_lua_tothread = (PFN_lua_tothread)dlsym(gge_handle, "lua_tothread");
    if (!proxy_lua_tothread && lua_handle) proxy_lua_tothread = (PFN_lua_tothread)dlsym(lua_handle, "lua_tothread");
    if (!proxy_lua_tothread) LOGE("Failed to resolve Lua symbol: lua_tothread\n");
    proxy_lua_topointer = (PFN_lua_topointer)dlsym(handle, "lua_topointer");
    if (!proxy_lua_topointer && gge_handle) proxy_lua_topointer = (PFN_lua_topointer)dlsym(gge_handle, "lua_topointer");
    if (!proxy_lua_topointer && lua_handle) proxy_lua_topointer = (PFN_lua_topointer)dlsym(lua_handle, "lua_topointer");
    if (!proxy_lua_topointer) LOGE("Failed to resolve Lua symbol: lua_topointer\n");
    proxy_lua_arith = (PFN_lua_arith)dlsym(handle, "lua_arith");
    if (!proxy_lua_arith && gge_handle) proxy_lua_arith = (PFN_lua_arith)dlsym(gge_handle, "lua_arith");
    if (!proxy_lua_arith && lua_handle) proxy_lua_arith = (PFN_lua_arith)dlsym(lua_handle, "lua_arith");
    if (!proxy_lua_arith) LOGE("Failed to resolve Lua symbol: lua_arith\n");
    proxy_lua_rawequal = (PFN_lua_rawequal)dlsym(handle, "lua_rawequal");
    if (!proxy_lua_rawequal && gge_handle) proxy_lua_rawequal = (PFN_lua_rawequal)dlsym(gge_handle, "lua_rawequal");
    if (!proxy_lua_rawequal && lua_handle) proxy_lua_rawequal = (PFN_lua_rawequal)dlsym(lua_handle, "lua_rawequal");
    if (!proxy_lua_rawequal) LOGE("Failed to resolve Lua symbol: lua_rawequal\n");
    proxy_lua_compare = (PFN_lua_compare)dlsym(handle, "lua_compare");
    if (!proxy_lua_compare && gge_handle) proxy_lua_compare = (PFN_lua_compare)dlsym(gge_handle, "lua_compare");
    if (!proxy_lua_compare && lua_handle) proxy_lua_compare = (PFN_lua_compare)dlsym(lua_handle, "lua_compare");
    if (!proxy_lua_compare) LOGE("Failed to resolve Lua symbol: lua_compare\n");
    proxy_lua_pushnil = (PFN_lua_pushnil)dlsym(handle, "lua_pushnil");
    if (!proxy_lua_pushnil && gge_handle) proxy_lua_pushnil = (PFN_lua_pushnil)dlsym(gge_handle, "lua_pushnil");
    if (!proxy_lua_pushnil && lua_handle) proxy_lua_pushnil = (PFN_lua_pushnil)dlsym(lua_handle, "lua_pushnil");
    if (!proxy_lua_pushnil) LOGE("Failed to resolve Lua symbol: lua_pushnil\n");
    proxy_lua_pushnumber = (PFN_lua_pushnumber)dlsym(handle, "lua_pushnumber");
    if (!proxy_lua_pushnumber && gge_handle) proxy_lua_pushnumber = (PFN_lua_pushnumber)dlsym(gge_handle, "lua_pushnumber");
    if (!proxy_lua_pushnumber && lua_handle) proxy_lua_pushnumber = (PFN_lua_pushnumber)dlsym(lua_handle, "lua_pushnumber");
    if (!proxy_lua_pushnumber) LOGE("Failed to resolve Lua symbol: lua_pushnumber\n");
    proxy_lua_pushinteger = (PFN_lua_pushinteger)dlsym(handle, "lua_pushinteger");
    if (!proxy_lua_pushinteger && gge_handle) proxy_lua_pushinteger = (PFN_lua_pushinteger)dlsym(gge_handle, "lua_pushinteger");
    if (!proxy_lua_pushinteger && lua_handle) proxy_lua_pushinteger = (PFN_lua_pushinteger)dlsym(lua_handle, "lua_pushinteger");
    if (!proxy_lua_pushinteger) LOGE("Failed to resolve Lua symbol: lua_pushinteger\n");
    proxy_lua_pushlstring = (PFN_lua_pushlstring)dlsym(handle, "lua_pushlstring");
    if (!proxy_lua_pushlstring && gge_handle) proxy_lua_pushlstring = (PFN_lua_pushlstring)dlsym(gge_handle, "lua_pushlstring");
    if (!proxy_lua_pushlstring && lua_handle) proxy_lua_pushlstring = (PFN_lua_pushlstring)dlsym(lua_handle, "lua_pushlstring");
    if (!proxy_lua_pushlstring) LOGE("Failed to resolve Lua symbol: lua_pushlstring\n");
    proxy_lua_pushstring = (PFN_lua_pushstring)dlsym(handle, "lua_pushstring");
    if (!proxy_lua_pushstring && gge_handle) proxy_lua_pushstring = (PFN_lua_pushstring)dlsym(gge_handle, "lua_pushstring");
    if (!proxy_lua_pushstring && lua_handle) proxy_lua_pushstring = (PFN_lua_pushstring)dlsym(lua_handle, "lua_pushstring");
    if (!proxy_lua_pushstring) LOGE("Failed to resolve Lua symbol: lua_pushstring\n");
    proxy_lua_pushvfstring = (PFN_lua_pushvfstring)dlsym(handle, "lua_pushvfstring");
    if (!proxy_lua_pushvfstring && gge_handle) proxy_lua_pushvfstring = (PFN_lua_pushvfstring)dlsym(gge_handle, "lua_pushvfstring");
    if (!proxy_lua_pushvfstring && lua_handle) proxy_lua_pushvfstring = (PFN_lua_pushvfstring)dlsym(lua_handle, "lua_pushvfstring");
    if (!proxy_lua_pushvfstring) LOGE("Failed to resolve Lua symbol: lua_pushvfstring\n");
    proxy_lua_pushfstring = (PFN_lua_pushfstring)dlsym(handle, "lua_pushfstring");
    if (!proxy_lua_pushfstring && gge_handle) proxy_lua_pushfstring = (PFN_lua_pushfstring)dlsym(gge_handle, "lua_pushfstring");
    if (!proxy_lua_pushfstring && lua_handle) proxy_lua_pushfstring = (PFN_lua_pushfstring)dlsym(lua_handle, "lua_pushfstring");
    if (!proxy_lua_pushfstring) LOGE("Failed to resolve Lua symbol: lua_pushfstring\n");
    proxy_lua_pushcclosure = (PFN_lua_pushcclosure)dlsym(handle, "lua_pushcclosure");
    if (!proxy_lua_pushcclosure && gge_handle) proxy_lua_pushcclosure = (PFN_lua_pushcclosure)dlsym(gge_handle, "lua_pushcclosure");
    if (!proxy_lua_pushcclosure && lua_handle) proxy_lua_pushcclosure = (PFN_lua_pushcclosure)dlsym(lua_handle, "lua_pushcclosure");
    if (!proxy_lua_pushcclosure) LOGE("Failed to resolve Lua symbol: lua_pushcclosure\n");
    proxy_lua_pushboolean = (PFN_lua_pushboolean)dlsym(handle, "lua_pushboolean");
    if (!proxy_lua_pushboolean && gge_handle) proxy_lua_pushboolean = (PFN_lua_pushboolean)dlsym(gge_handle, "lua_pushboolean");
    if (!proxy_lua_pushboolean && lua_handle) proxy_lua_pushboolean = (PFN_lua_pushboolean)dlsym(lua_handle, "lua_pushboolean");
    if (!proxy_lua_pushboolean) LOGE("Failed to resolve Lua symbol: lua_pushboolean\n");
    proxy_lua_pushlightuserdata = (PFN_lua_pushlightuserdata)dlsym(handle, "lua_pushlightuserdata");
    if (!proxy_lua_pushlightuserdata && gge_handle) proxy_lua_pushlightuserdata = (PFN_lua_pushlightuserdata)dlsym(gge_handle, "lua_pushlightuserdata");
    if (!proxy_lua_pushlightuserdata && lua_handle) proxy_lua_pushlightuserdata = (PFN_lua_pushlightuserdata)dlsym(lua_handle, "lua_pushlightuserdata");
    if (!proxy_lua_pushlightuserdata) LOGE("Failed to resolve Lua symbol: lua_pushlightuserdata\n");
    proxy_lua_pushthread = (PFN_lua_pushthread)dlsym(handle, "lua_pushthread");
    if (!proxy_lua_pushthread && gge_handle) proxy_lua_pushthread = (PFN_lua_pushthread)dlsym(gge_handle, "lua_pushthread");
    if (!proxy_lua_pushthread && lua_handle) proxy_lua_pushthread = (PFN_lua_pushthread)dlsym(lua_handle, "lua_pushthread");
    if (!proxy_lua_pushthread) LOGE("Failed to resolve Lua symbol: lua_pushthread\n");
    proxy_lua_getglobal = (PFN_lua_getglobal)dlsym(handle, "lua_getglobal");
    if (!proxy_lua_getglobal && gge_handle) proxy_lua_getglobal = (PFN_lua_getglobal)dlsym(gge_handle, "lua_getglobal");
    if (!proxy_lua_getglobal && lua_handle) proxy_lua_getglobal = (PFN_lua_getglobal)dlsym(lua_handle, "lua_getglobal");
    if (!proxy_lua_getglobal) LOGE("Failed to resolve Lua symbol: lua_getglobal\n");
    proxy_lua_gettable = (PFN_lua_gettable)dlsym(handle, "lua_gettable");
    if (!proxy_lua_gettable && gge_handle) proxy_lua_gettable = (PFN_lua_gettable)dlsym(gge_handle, "lua_gettable");
    if (!proxy_lua_gettable && lua_handle) proxy_lua_gettable = (PFN_lua_gettable)dlsym(lua_handle, "lua_gettable");
    if (!proxy_lua_gettable) LOGE("Failed to resolve Lua symbol: lua_gettable\n");
    proxy_lua_getfield = (PFN_lua_getfield)dlsym(handle, "lua_getfield");
    if (!proxy_lua_getfield && gge_handle) proxy_lua_getfield = (PFN_lua_getfield)dlsym(gge_handle, "lua_getfield");
    if (!proxy_lua_getfield && lua_handle) proxy_lua_getfield = (PFN_lua_getfield)dlsym(lua_handle, "lua_getfield");
    if (!proxy_lua_getfield) LOGE("Failed to resolve Lua symbol: lua_getfield\n");
    proxy_lua_geti = (PFN_lua_geti)dlsym(handle, "lua_geti");
    if (!proxy_lua_geti && gge_handle) proxy_lua_geti = (PFN_lua_geti)dlsym(gge_handle, "lua_geti");
    if (!proxy_lua_geti && lua_handle) proxy_lua_geti = (PFN_lua_geti)dlsym(lua_handle, "lua_geti");
    if (!proxy_lua_geti) LOGE("Failed to resolve Lua symbol: lua_geti\n");
    proxy_lua_rawget = (PFN_lua_rawget)dlsym(handle, "lua_rawget");
    if (!proxy_lua_rawget && gge_handle) proxy_lua_rawget = (PFN_lua_rawget)dlsym(gge_handle, "lua_rawget");
    if (!proxy_lua_rawget && lua_handle) proxy_lua_rawget = (PFN_lua_rawget)dlsym(lua_handle, "lua_rawget");
    if (!proxy_lua_rawget) LOGE("Failed to resolve Lua symbol: lua_rawget\n");
    proxy_lua_rawgeti = (PFN_lua_rawgeti)dlsym(handle, "lua_rawgeti");
    if (!proxy_lua_rawgeti && gge_handle) proxy_lua_rawgeti = (PFN_lua_rawgeti)dlsym(gge_handle, "lua_rawgeti");
    if (!proxy_lua_rawgeti && lua_handle) proxy_lua_rawgeti = (PFN_lua_rawgeti)dlsym(lua_handle, "lua_rawgeti");
    if (!proxy_lua_rawgeti) LOGE("Failed to resolve Lua symbol: lua_rawgeti\n");
    proxy_lua_rawgetp = (PFN_lua_rawgetp)dlsym(handle, "lua_rawgetp");
    if (!proxy_lua_rawgetp && gge_handle) proxy_lua_rawgetp = (PFN_lua_rawgetp)dlsym(gge_handle, "lua_rawgetp");
    if (!proxy_lua_rawgetp && lua_handle) proxy_lua_rawgetp = (PFN_lua_rawgetp)dlsym(lua_handle, "lua_rawgetp");
    if (!proxy_lua_rawgetp) LOGE("Failed to resolve Lua symbol: lua_rawgetp\n");
    proxy_lua_createtable = (PFN_lua_createtable)dlsym(handle, "lua_createtable");
    if (!proxy_lua_createtable && gge_handle) proxy_lua_createtable = (PFN_lua_createtable)dlsym(gge_handle, "lua_createtable");
    if (!proxy_lua_createtable && lua_handle) proxy_lua_createtable = (PFN_lua_createtable)dlsym(lua_handle, "lua_createtable");
    if (!proxy_lua_createtable) LOGE("Failed to resolve Lua symbol: lua_createtable\n");
    proxy_lua_newuserdatauv = (PFN_lua_newuserdatauv)dlsym(handle, "lua_newuserdatauv");
    if (!proxy_lua_newuserdatauv && gge_handle) proxy_lua_newuserdatauv = (PFN_lua_newuserdatauv)dlsym(gge_handle, "lua_newuserdatauv");
    if (!proxy_lua_newuserdatauv && lua_handle) proxy_lua_newuserdatauv = (PFN_lua_newuserdatauv)dlsym(lua_handle, "lua_newuserdatauv");
    if (!proxy_lua_newuserdatauv) LOGE("Failed to resolve Lua symbol: lua_newuserdatauv\n");
    proxy_lua_getmetatable = (PFN_lua_getmetatable)dlsym(handle, "lua_getmetatable");
    if (!proxy_lua_getmetatable && gge_handle) proxy_lua_getmetatable = (PFN_lua_getmetatable)dlsym(gge_handle, "lua_getmetatable");
    if (!proxy_lua_getmetatable && lua_handle) proxy_lua_getmetatable = (PFN_lua_getmetatable)dlsym(lua_handle, "lua_getmetatable");
    if (!proxy_lua_getmetatable) LOGE("Failed to resolve Lua symbol: lua_getmetatable\n");
    proxy_lua_getiuservalue = (PFN_lua_getiuservalue)dlsym(handle, "lua_getiuservalue");
    if (!proxy_lua_getiuservalue && gge_handle) proxy_lua_getiuservalue = (PFN_lua_getiuservalue)dlsym(gge_handle, "lua_getiuservalue");
    if (!proxy_lua_getiuservalue && lua_handle) proxy_lua_getiuservalue = (PFN_lua_getiuservalue)dlsym(lua_handle, "lua_getiuservalue");
    if (!proxy_lua_getiuservalue) LOGE("Failed to resolve Lua symbol: lua_getiuservalue\n");
    proxy_lua_setglobal = (PFN_lua_setglobal)dlsym(handle, "lua_setglobal");
    if (!proxy_lua_setglobal && gge_handle) proxy_lua_setglobal = (PFN_lua_setglobal)dlsym(gge_handle, "lua_setglobal");
    if (!proxy_lua_setglobal && lua_handle) proxy_lua_setglobal = (PFN_lua_setglobal)dlsym(lua_handle, "lua_setglobal");
    if (!proxy_lua_setglobal) LOGE("Failed to resolve Lua symbol: lua_setglobal\n");
    proxy_lua_settable = (PFN_lua_settable)dlsym(handle, "lua_settable");
    if (!proxy_lua_settable && gge_handle) proxy_lua_settable = (PFN_lua_settable)dlsym(gge_handle, "lua_settable");
    if (!proxy_lua_settable && lua_handle) proxy_lua_settable = (PFN_lua_settable)dlsym(lua_handle, "lua_settable");
    if (!proxy_lua_settable) LOGE("Failed to resolve Lua symbol: lua_settable\n");
    proxy_lua_setfield = (PFN_lua_setfield)dlsym(handle, "lua_setfield");
    if (!proxy_lua_setfield && gge_handle) proxy_lua_setfield = (PFN_lua_setfield)dlsym(gge_handle, "lua_setfield");
    if (!proxy_lua_setfield && lua_handle) proxy_lua_setfield = (PFN_lua_setfield)dlsym(lua_handle, "lua_setfield");
    if (!proxy_lua_setfield) LOGE("Failed to resolve Lua symbol: lua_setfield\n");
    proxy_lua_seti = (PFN_lua_seti)dlsym(handle, "lua_seti");
    if (!proxy_lua_seti && gge_handle) proxy_lua_seti = (PFN_lua_seti)dlsym(gge_handle, "lua_seti");
    if (!proxy_lua_seti && lua_handle) proxy_lua_seti = (PFN_lua_seti)dlsym(lua_handle, "lua_seti");
    if (!proxy_lua_seti) LOGE("Failed to resolve Lua symbol: lua_seti\n");
    proxy_lua_rawset = (PFN_lua_rawset)dlsym(handle, "lua_rawset");
    if (!proxy_lua_rawset && gge_handle) proxy_lua_rawset = (PFN_lua_rawset)dlsym(gge_handle, "lua_rawset");
    if (!proxy_lua_rawset && lua_handle) proxy_lua_rawset = (PFN_lua_rawset)dlsym(lua_handle, "lua_rawset");
    if (!proxy_lua_rawset) LOGE("Failed to resolve Lua symbol: lua_rawset\n");
    proxy_lua_rawseti = (PFN_lua_rawseti)dlsym(handle, "lua_rawseti");
    if (!proxy_lua_rawseti && gge_handle) proxy_lua_rawseti = (PFN_lua_rawseti)dlsym(gge_handle, "lua_rawseti");
    if (!proxy_lua_rawseti && lua_handle) proxy_lua_rawseti = (PFN_lua_rawseti)dlsym(lua_handle, "lua_rawseti");
    if (!proxy_lua_rawseti) LOGE("Failed to resolve Lua symbol: lua_rawseti\n");
    proxy_lua_rawsetp = (PFN_lua_rawsetp)dlsym(handle, "lua_rawsetp");
    if (!proxy_lua_rawsetp && gge_handle) proxy_lua_rawsetp = (PFN_lua_rawsetp)dlsym(gge_handle, "lua_rawsetp");
    if (!proxy_lua_rawsetp && lua_handle) proxy_lua_rawsetp = (PFN_lua_rawsetp)dlsym(lua_handle, "lua_rawsetp");
    if (!proxy_lua_rawsetp) LOGE("Failed to resolve Lua symbol: lua_rawsetp\n");
    proxy_lua_setmetatable = (PFN_lua_setmetatable)dlsym(handle, "lua_setmetatable");
    if (!proxy_lua_setmetatable && gge_handle) proxy_lua_setmetatable = (PFN_lua_setmetatable)dlsym(gge_handle, "lua_setmetatable");
    if (!proxy_lua_setmetatable && lua_handle) proxy_lua_setmetatable = (PFN_lua_setmetatable)dlsym(lua_handle, "lua_setmetatable");
    if (!proxy_lua_setmetatable) LOGE("Failed to resolve Lua symbol: lua_setmetatable\n");
    proxy_lua_setiuservalue = (PFN_lua_setiuservalue)dlsym(handle, "lua_setiuservalue");
    if (!proxy_lua_setiuservalue && gge_handle) proxy_lua_setiuservalue = (PFN_lua_setiuservalue)dlsym(gge_handle, "lua_setiuservalue");
    if (!proxy_lua_setiuservalue && lua_handle) proxy_lua_setiuservalue = (PFN_lua_setiuservalue)dlsym(lua_handle, "lua_setiuservalue");
    if (!proxy_lua_setiuservalue) LOGE("Failed to resolve Lua symbol: lua_setiuservalue\n");
    proxy_lua_callk = (PFN_lua_callk)dlsym(handle, "lua_callk");
    if (!proxy_lua_callk && gge_handle) proxy_lua_callk = (PFN_lua_callk)dlsym(gge_handle, "lua_callk");
    if (!proxy_lua_callk && lua_handle) proxy_lua_callk = (PFN_lua_callk)dlsym(lua_handle, "lua_callk");
    if (!proxy_lua_callk) LOGE("Failed to resolve Lua symbol: lua_callk\n");
    proxy_lua_pcallk = (PFN_lua_pcallk)dlsym(handle, "lua_pcallk");
    if (!proxy_lua_pcallk && gge_handle) proxy_lua_pcallk = (PFN_lua_pcallk)dlsym(gge_handle, "lua_pcallk");
    if (!proxy_lua_pcallk && lua_handle) proxy_lua_pcallk = (PFN_lua_pcallk)dlsym(lua_handle, "lua_pcallk");
    if (!proxy_lua_pcallk) LOGE("Failed to resolve Lua symbol: lua_pcallk\n");
    proxy_lua_load = (PFN_lua_load)dlsym(handle, "lua_load");
    if (!proxy_lua_load && gge_handle) proxy_lua_load = (PFN_lua_load)dlsym(gge_handle, "lua_load");
    if (!proxy_lua_load && lua_handle) proxy_lua_load = (PFN_lua_load)dlsym(lua_handle, "lua_load");
    if (!proxy_lua_load) LOGE("Failed to resolve Lua symbol: lua_load\n");
    proxy_lua_dump = (PFN_lua_dump)dlsym(handle, "lua_dump");
    if (!proxy_lua_dump && gge_handle) proxy_lua_dump = (PFN_lua_dump)dlsym(gge_handle, "lua_dump");
    if (!proxy_lua_dump && lua_handle) proxy_lua_dump = (PFN_lua_dump)dlsym(lua_handle, "lua_dump");
    if (!proxy_lua_dump) LOGE("Failed to resolve Lua symbol: lua_dump\n");
    proxy_lua_yieldk = (PFN_lua_yieldk)dlsym(handle, "lua_yieldk");
    if (!proxy_lua_yieldk && gge_handle) proxy_lua_yieldk = (PFN_lua_yieldk)dlsym(gge_handle, "lua_yieldk");
    if (!proxy_lua_yieldk && lua_handle) proxy_lua_yieldk = (PFN_lua_yieldk)dlsym(lua_handle, "lua_yieldk");
    if (!proxy_lua_yieldk) LOGE("Failed to resolve Lua symbol: lua_yieldk\n");
    proxy_lua_resume = (PFN_lua_resume)dlsym(handle, "lua_resume");
    if (!proxy_lua_resume && gge_handle) proxy_lua_resume = (PFN_lua_resume)dlsym(gge_handle, "lua_resume");
    if (!proxy_lua_resume && lua_handle) proxy_lua_resume = (PFN_lua_resume)dlsym(lua_handle, "lua_resume");
    if (!proxy_lua_resume) LOGE("Failed to resolve Lua symbol: lua_resume\n");
    proxy_lua_status = (PFN_lua_status)dlsym(handle, "lua_status");
    if (!proxy_lua_status && gge_handle) proxy_lua_status = (PFN_lua_status)dlsym(gge_handle, "lua_status");
    if (!proxy_lua_status && lua_handle) proxy_lua_status = (PFN_lua_status)dlsym(lua_handle, "lua_status");
    if (!proxy_lua_status) LOGE("Failed to resolve Lua symbol: lua_status\n");
    proxy_lua_isyieldable = (PFN_lua_isyieldable)dlsym(handle, "lua_isyieldable");
    if (!proxy_lua_isyieldable && gge_handle) proxy_lua_isyieldable = (PFN_lua_isyieldable)dlsym(gge_handle, "lua_isyieldable");
    if (!proxy_lua_isyieldable && lua_handle) proxy_lua_isyieldable = (PFN_lua_isyieldable)dlsym(lua_handle, "lua_isyieldable");
    if (!proxy_lua_isyieldable) LOGE("Failed to resolve Lua symbol: lua_isyieldable\n");
    proxy_lua_setwarnf = (PFN_lua_setwarnf)dlsym(handle, "lua_setwarnf");
    if (!proxy_lua_setwarnf && gge_handle) proxy_lua_setwarnf = (PFN_lua_setwarnf)dlsym(gge_handle, "lua_setwarnf");
    if (!proxy_lua_setwarnf && lua_handle) proxy_lua_setwarnf = (PFN_lua_setwarnf)dlsym(lua_handle, "lua_setwarnf");
    if (!proxy_lua_setwarnf) LOGE("Failed to resolve Lua symbol: lua_setwarnf\n");
    proxy_lua_warning = (PFN_lua_warning)dlsym(handle, "lua_warning");
    if (!proxy_lua_warning && gge_handle) proxy_lua_warning = (PFN_lua_warning)dlsym(gge_handle, "lua_warning");
    if (!proxy_lua_warning && lua_handle) proxy_lua_warning = (PFN_lua_warning)dlsym(lua_handle, "lua_warning");
    if (!proxy_lua_warning) LOGE("Failed to resolve Lua symbol: lua_warning\n");
    proxy_lua_gc = (PFN_lua_gc)dlsym(handle, "lua_gc");
    if (!proxy_lua_gc && gge_handle) proxy_lua_gc = (PFN_lua_gc)dlsym(gge_handle, "lua_gc");
    if (!proxy_lua_gc && lua_handle) proxy_lua_gc = (PFN_lua_gc)dlsym(lua_handle, "lua_gc");
    if (!proxy_lua_gc) LOGE("Failed to resolve Lua symbol: lua_gc\n");
    proxy_lua_error = (PFN_lua_error)dlsym(handle, "lua_error");
    if (!proxy_lua_error && gge_handle) proxy_lua_error = (PFN_lua_error)dlsym(gge_handle, "lua_error");
    if (!proxy_lua_error && lua_handle) proxy_lua_error = (PFN_lua_error)dlsym(lua_handle, "lua_error");
    if (!proxy_lua_error) LOGE("Failed to resolve Lua symbol: lua_error\n");
    proxy_lua_next = (PFN_lua_next)dlsym(handle, "lua_next");
    if (!proxy_lua_next && gge_handle) proxy_lua_next = (PFN_lua_next)dlsym(gge_handle, "lua_next");
    if (!proxy_lua_next && lua_handle) proxy_lua_next = (PFN_lua_next)dlsym(lua_handle, "lua_next");
    if (!proxy_lua_next) LOGE("Failed to resolve Lua symbol: lua_next\n");
    proxy_lua_concat = (PFN_lua_concat)dlsym(handle, "lua_concat");
    if (!proxy_lua_concat && gge_handle) proxy_lua_concat = (PFN_lua_concat)dlsym(gge_handle, "lua_concat");
    if (!proxy_lua_concat && lua_handle) proxy_lua_concat = (PFN_lua_concat)dlsym(lua_handle, "lua_concat");
    if (!proxy_lua_concat) LOGE("Failed to resolve Lua symbol: lua_concat\n");
    proxy_lua_len = (PFN_lua_len)dlsym(handle, "lua_len");
    if (!proxy_lua_len && gge_handle) proxy_lua_len = (PFN_lua_len)dlsym(gge_handle, "lua_len");
    if (!proxy_lua_len && lua_handle) proxy_lua_len = (PFN_lua_len)dlsym(lua_handle, "lua_len");
    if (!proxy_lua_len) LOGE("Failed to resolve Lua symbol: lua_len\n");
    proxy_lua_stringtonumber = (PFN_lua_stringtonumber)dlsym(handle, "lua_stringtonumber");
    if (!proxy_lua_stringtonumber && gge_handle) proxy_lua_stringtonumber = (PFN_lua_stringtonumber)dlsym(gge_handle, "lua_stringtonumber");
    if (!proxy_lua_stringtonumber && lua_handle) proxy_lua_stringtonumber = (PFN_lua_stringtonumber)dlsym(lua_handle, "lua_stringtonumber");
    if (!proxy_lua_stringtonumber) LOGE("Failed to resolve Lua symbol: lua_stringtonumber\n");
    proxy_lua_getallocf = (PFN_lua_getallocf)dlsym(handle, "lua_getallocf");
    if (!proxy_lua_getallocf && gge_handle) proxy_lua_getallocf = (PFN_lua_getallocf)dlsym(gge_handle, "lua_getallocf");
    if (!proxy_lua_getallocf && lua_handle) proxy_lua_getallocf = (PFN_lua_getallocf)dlsym(lua_handle, "lua_getallocf");
    if (!proxy_lua_getallocf) LOGE("Failed to resolve Lua symbol: lua_getallocf\n");
    proxy_lua_setallocf = (PFN_lua_setallocf)dlsym(handle, "lua_setallocf");
    if (!proxy_lua_setallocf && gge_handle) proxy_lua_setallocf = (PFN_lua_setallocf)dlsym(gge_handle, "lua_setallocf");
    if (!proxy_lua_setallocf && lua_handle) proxy_lua_setallocf = (PFN_lua_setallocf)dlsym(lua_handle, "lua_setallocf");
    if (!proxy_lua_setallocf) LOGE("Failed to resolve Lua symbol: lua_setallocf\n");
    proxy_lua_toclose = (PFN_lua_toclose)dlsym(handle, "lua_toclose");
    if (!proxy_lua_toclose && gge_handle) proxy_lua_toclose = (PFN_lua_toclose)dlsym(gge_handle, "lua_toclose");
    if (!proxy_lua_toclose && lua_handle) proxy_lua_toclose = (PFN_lua_toclose)dlsym(lua_handle, "lua_toclose");
    if (!proxy_lua_toclose) LOGE("Failed to resolve Lua symbol: lua_toclose\n");
    proxy_lua_closeslot = (PFN_lua_closeslot)dlsym(handle, "lua_closeslot");
    if (!proxy_lua_closeslot && gge_handle) proxy_lua_closeslot = (PFN_lua_closeslot)dlsym(gge_handle, "lua_closeslot");
    if (!proxy_lua_closeslot && lua_handle) proxy_lua_closeslot = (PFN_lua_closeslot)dlsym(lua_handle, "lua_closeslot");
    if (!proxy_lua_closeslot) LOGE("Failed to resolve Lua symbol: lua_closeslot\n");
    proxy_lua_getstack = (PFN_lua_getstack)dlsym(handle, "lua_getstack");
    if (!proxy_lua_getstack && gge_handle) proxy_lua_getstack = (PFN_lua_getstack)dlsym(gge_handle, "lua_getstack");
    if (!proxy_lua_getstack && lua_handle) proxy_lua_getstack = (PFN_lua_getstack)dlsym(lua_handle, "lua_getstack");
    if (!proxy_lua_getstack) LOGE("Failed to resolve Lua symbol: lua_getstack\n");
    proxy_lua_getinfo = (PFN_lua_getinfo)dlsym(handle, "lua_getinfo");
    if (!proxy_lua_getinfo && gge_handle) proxy_lua_getinfo = (PFN_lua_getinfo)dlsym(gge_handle, "lua_getinfo");
    if (!proxy_lua_getinfo && lua_handle) proxy_lua_getinfo = (PFN_lua_getinfo)dlsym(lua_handle, "lua_getinfo");
    if (!proxy_lua_getinfo) LOGE("Failed to resolve Lua symbol: lua_getinfo\n");
    proxy_lua_getlocal = (PFN_lua_getlocal)dlsym(handle, "lua_getlocal");
    if (!proxy_lua_getlocal && gge_handle) proxy_lua_getlocal = (PFN_lua_getlocal)dlsym(gge_handle, "lua_getlocal");
    if (!proxy_lua_getlocal && lua_handle) proxy_lua_getlocal = (PFN_lua_getlocal)dlsym(lua_handle, "lua_getlocal");
    if (!proxy_lua_getlocal) LOGE("Failed to resolve Lua symbol: lua_getlocal\n");
    proxy_lua_setlocal = (PFN_lua_setlocal)dlsym(handle, "lua_setlocal");
    if (!proxy_lua_setlocal && gge_handle) proxy_lua_setlocal = (PFN_lua_setlocal)dlsym(gge_handle, "lua_setlocal");
    if (!proxy_lua_setlocal && lua_handle) proxy_lua_setlocal = (PFN_lua_setlocal)dlsym(lua_handle, "lua_setlocal");
    if (!proxy_lua_setlocal) LOGE("Failed to resolve Lua symbol: lua_setlocal\n");
    proxy_lua_getupvalue = (PFN_lua_getupvalue)dlsym(handle, "lua_getupvalue");
    if (!proxy_lua_getupvalue && gge_handle) proxy_lua_getupvalue = (PFN_lua_getupvalue)dlsym(gge_handle, "lua_getupvalue");
    if (!proxy_lua_getupvalue && lua_handle) proxy_lua_getupvalue = (PFN_lua_getupvalue)dlsym(lua_handle, "lua_getupvalue");
    if (!proxy_lua_getupvalue) LOGE("Failed to resolve Lua symbol: lua_getupvalue\n");
    proxy_lua_setupvalue = (PFN_lua_setupvalue)dlsym(handle, "lua_setupvalue");
    if (!proxy_lua_setupvalue && gge_handle) proxy_lua_setupvalue = (PFN_lua_setupvalue)dlsym(gge_handle, "lua_setupvalue");
    if (!proxy_lua_setupvalue && lua_handle) proxy_lua_setupvalue = (PFN_lua_setupvalue)dlsym(lua_handle, "lua_setupvalue");
    if (!proxy_lua_setupvalue) LOGE("Failed to resolve Lua symbol: lua_setupvalue\n");
    proxy_lua_upvalueid = (PFN_lua_upvalueid)dlsym(handle, "lua_upvalueid");
    if (!proxy_lua_upvalueid && gge_handle) proxy_lua_upvalueid = (PFN_lua_upvalueid)dlsym(gge_handle, "lua_upvalueid");
    if (!proxy_lua_upvalueid && lua_handle) proxy_lua_upvalueid = (PFN_lua_upvalueid)dlsym(lua_handle, "lua_upvalueid");
    if (!proxy_lua_upvalueid) LOGE("Failed to resolve Lua symbol: lua_upvalueid\n");
    proxy_lua_upvaluejoin = (PFN_lua_upvaluejoin)dlsym(handle, "lua_upvaluejoin");
    if (!proxy_lua_upvaluejoin && gge_handle) proxy_lua_upvaluejoin = (PFN_lua_upvaluejoin)dlsym(gge_handle, "lua_upvaluejoin");
    if (!proxy_lua_upvaluejoin && lua_handle) proxy_lua_upvaluejoin = (PFN_lua_upvaluejoin)dlsym(lua_handle, "lua_upvaluejoin");
    if (!proxy_lua_upvaluejoin) LOGE("Failed to resolve Lua symbol: lua_upvaluejoin\n");
    proxy_lua_sethook = (PFN_lua_sethook)dlsym(handle, "lua_sethook");
    if (!proxy_lua_sethook && gge_handle) proxy_lua_sethook = (PFN_lua_sethook)dlsym(gge_handle, "lua_sethook");
    if (!proxy_lua_sethook && lua_handle) proxy_lua_sethook = (PFN_lua_sethook)dlsym(lua_handle, "lua_sethook");
    if (!proxy_lua_sethook) LOGE("Failed to resolve Lua symbol: lua_sethook\n");
    proxy_lua_gethook = (PFN_lua_gethook)dlsym(handle, "lua_gethook");
    if (!proxy_lua_gethook && gge_handle) proxy_lua_gethook = (PFN_lua_gethook)dlsym(gge_handle, "lua_gethook");
    if (!proxy_lua_gethook && lua_handle) proxy_lua_gethook = (PFN_lua_gethook)dlsym(lua_handle, "lua_gethook");
    if (!proxy_lua_gethook) LOGE("Failed to resolve Lua symbol: lua_gethook\n");
    proxy_lua_gethookmask = (PFN_lua_gethookmask)dlsym(handle, "lua_gethookmask");
    if (!proxy_lua_gethookmask && gge_handle) proxy_lua_gethookmask = (PFN_lua_gethookmask)dlsym(gge_handle, "lua_gethookmask");
    if (!proxy_lua_gethookmask && lua_handle) proxy_lua_gethookmask = (PFN_lua_gethookmask)dlsym(lua_handle, "lua_gethookmask");
    if (!proxy_lua_gethookmask) LOGE("Failed to resolve Lua symbol: lua_gethookmask\n");
    proxy_lua_gethookcount = (PFN_lua_gethookcount)dlsym(handle, "lua_gethookcount");
    if (!proxy_lua_gethookcount && gge_handle) proxy_lua_gethookcount = (PFN_lua_gethookcount)dlsym(gge_handle, "lua_gethookcount");
    if (!proxy_lua_gethookcount && lua_handle) proxy_lua_gethookcount = (PFN_lua_gethookcount)dlsym(lua_handle, "lua_gethookcount");
    if (!proxy_lua_gethookcount) LOGE("Failed to resolve Lua symbol: lua_gethookcount\n");
    proxy_lua_setcstacklimit = (PFN_lua_setcstacklimit)dlsym(handle, "lua_setcstacklimit");
    if (!proxy_lua_setcstacklimit && gge_handle) proxy_lua_setcstacklimit = (PFN_lua_setcstacklimit)dlsym(gge_handle, "lua_setcstacklimit");
    if (!proxy_lua_setcstacklimit && lua_handle) proxy_lua_setcstacklimit = (PFN_lua_setcstacklimit)dlsym(lua_handle, "lua_setcstacklimit");
    if (!proxy_lua_setcstacklimit) LOGE("Failed to resolve Lua symbol: lua_setcstacklimit\n");
    proxy_luaL_checkversion_ = (PFN_luaL_checkversion_)dlsym(handle, "luaL_checkversion_");
    if (!proxy_luaL_checkversion_ && gge_handle) proxy_luaL_checkversion_ = (PFN_luaL_checkversion_)dlsym(gge_handle, "luaL_checkversion_");
    if (!proxy_luaL_checkversion_ && lua_handle) proxy_luaL_checkversion_ = (PFN_luaL_checkversion_)dlsym(lua_handle, "luaL_checkversion_");
    if (!proxy_luaL_checkversion_) LOGE("Failed to resolve Lua symbol: luaL_checkversion_\n");
    proxy_luaL_getmetafield = (PFN_luaL_getmetafield)dlsym(handle, "luaL_getmetafield");
    if (!proxy_luaL_getmetafield && gge_handle) proxy_luaL_getmetafield = (PFN_luaL_getmetafield)dlsym(gge_handle, "luaL_getmetafield");
    if (!proxy_luaL_getmetafield && lua_handle) proxy_luaL_getmetafield = (PFN_luaL_getmetafield)dlsym(lua_handle, "luaL_getmetafield");
    if (!proxy_luaL_getmetafield) LOGE("Failed to resolve Lua symbol: luaL_getmetafield\n");
    proxy_luaL_callmeta = (PFN_luaL_callmeta)dlsym(handle, "luaL_callmeta");
    if (!proxy_luaL_callmeta && gge_handle) proxy_luaL_callmeta = (PFN_luaL_callmeta)dlsym(gge_handle, "luaL_callmeta");
    if (!proxy_luaL_callmeta && lua_handle) proxy_luaL_callmeta = (PFN_luaL_callmeta)dlsym(lua_handle, "luaL_callmeta");
    if (!proxy_luaL_callmeta) LOGE("Failed to resolve Lua symbol: luaL_callmeta\n");
    proxy_luaL_tolstring = (PFN_luaL_tolstring)dlsym(handle, "luaL_tolstring");
    if (!proxy_luaL_tolstring && gge_handle) proxy_luaL_tolstring = (PFN_luaL_tolstring)dlsym(gge_handle, "luaL_tolstring");
    if (!proxy_luaL_tolstring && lua_handle) proxy_luaL_tolstring = (PFN_luaL_tolstring)dlsym(lua_handle, "luaL_tolstring");
    if (!proxy_luaL_tolstring) LOGE("Failed to resolve Lua symbol: luaL_tolstring\n");
    proxy_luaL_argerror = (PFN_luaL_argerror)dlsym(handle, "luaL_argerror");
    if (!proxy_luaL_argerror && gge_handle) proxy_luaL_argerror = (PFN_luaL_argerror)dlsym(gge_handle, "luaL_argerror");
    if (!proxy_luaL_argerror && lua_handle) proxy_luaL_argerror = (PFN_luaL_argerror)dlsym(lua_handle, "luaL_argerror");
    if (!proxy_luaL_argerror) LOGE("Failed to resolve Lua symbol: luaL_argerror\n");
    proxy_luaL_typeerror = (PFN_luaL_typeerror)dlsym(handle, "luaL_typeerror");
    if (!proxy_luaL_typeerror && gge_handle) proxy_luaL_typeerror = (PFN_luaL_typeerror)dlsym(gge_handle, "luaL_typeerror");
    if (!proxy_luaL_typeerror && lua_handle) proxy_luaL_typeerror = (PFN_luaL_typeerror)dlsym(lua_handle, "luaL_typeerror");
    if (!proxy_luaL_typeerror) LOGE("Failed to resolve Lua symbol: luaL_typeerror\n");
    proxy_luaL_checklstring = (PFN_luaL_checklstring)dlsym(handle, "luaL_checklstring");
    if (!proxy_luaL_checklstring && gge_handle) proxy_luaL_checklstring = (PFN_luaL_checklstring)dlsym(gge_handle, "luaL_checklstring");
    if (!proxy_luaL_checklstring && lua_handle) proxy_luaL_checklstring = (PFN_luaL_checklstring)dlsym(lua_handle, "luaL_checklstring");
    if (!proxy_luaL_checklstring) LOGE("Failed to resolve Lua symbol: luaL_checklstring\n");
    proxy_luaL_optlstring = (PFN_luaL_optlstring)dlsym(handle, "luaL_optlstring");
    if (!proxy_luaL_optlstring && gge_handle) proxy_luaL_optlstring = (PFN_luaL_optlstring)dlsym(gge_handle, "luaL_optlstring");
    if (!proxy_luaL_optlstring && lua_handle) proxy_luaL_optlstring = (PFN_luaL_optlstring)dlsym(lua_handle, "luaL_optlstring");
    if (!proxy_luaL_optlstring) LOGE("Failed to resolve Lua symbol: luaL_optlstring\n");
    proxy_luaL_checknumber = (PFN_luaL_checknumber)dlsym(handle, "luaL_checknumber");
    if (!proxy_luaL_checknumber && gge_handle) proxy_luaL_checknumber = (PFN_luaL_checknumber)dlsym(gge_handle, "luaL_checknumber");
    if (!proxy_luaL_checknumber && lua_handle) proxy_luaL_checknumber = (PFN_luaL_checknumber)dlsym(lua_handle, "luaL_checknumber");
    if (!proxy_luaL_checknumber) LOGE("Failed to resolve Lua symbol: luaL_checknumber\n");
    proxy_luaL_optnumber = (PFN_luaL_optnumber)dlsym(handle, "luaL_optnumber");
    if (!proxy_luaL_optnumber && gge_handle) proxy_luaL_optnumber = (PFN_luaL_optnumber)dlsym(gge_handle, "luaL_optnumber");
    if (!proxy_luaL_optnumber && lua_handle) proxy_luaL_optnumber = (PFN_luaL_optnumber)dlsym(lua_handle, "luaL_optnumber");
    if (!proxy_luaL_optnumber) LOGE("Failed to resolve Lua symbol: luaL_optnumber\n");
    proxy_luaL_checkinteger = (PFN_luaL_checkinteger)dlsym(handle, "luaL_checkinteger");
    if (!proxy_luaL_checkinteger && gge_handle) proxy_luaL_checkinteger = (PFN_luaL_checkinteger)dlsym(gge_handle, "luaL_checkinteger");
    if (!proxy_luaL_checkinteger && lua_handle) proxy_luaL_checkinteger = (PFN_luaL_checkinteger)dlsym(lua_handle, "luaL_checkinteger");
    if (!proxy_luaL_checkinteger) LOGE("Failed to resolve Lua symbol: luaL_checkinteger\n");
    proxy_luaL_optinteger = (PFN_luaL_optinteger)dlsym(handle, "luaL_optinteger");
    if (!proxy_luaL_optinteger && gge_handle) proxy_luaL_optinteger = (PFN_luaL_optinteger)dlsym(gge_handle, "luaL_optinteger");
    if (!proxy_luaL_optinteger && lua_handle) proxy_luaL_optinteger = (PFN_luaL_optinteger)dlsym(lua_handle, "luaL_optinteger");
    if (!proxy_luaL_optinteger) LOGE("Failed to resolve Lua symbol: luaL_optinteger\n");
    proxy_luaL_checkstack = (PFN_luaL_checkstack)dlsym(handle, "luaL_checkstack");
    if (!proxy_luaL_checkstack && gge_handle) proxy_luaL_checkstack = (PFN_luaL_checkstack)dlsym(gge_handle, "luaL_checkstack");
    if (!proxy_luaL_checkstack && lua_handle) proxy_luaL_checkstack = (PFN_luaL_checkstack)dlsym(lua_handle, "luaL_checkstack");
    if (!proxy_luaL_checkstack) LOGE("Failed to resolve Lua symbol: luaL_checkstack\n");
    proxy_luaL_checktype = (PFN_luaL_checktype)dlsym(handle, "luaL_checktype");
    if (!proxy_luaL_checktype && gge_handle) proxy_luaL_checktype = (PFN_luaL_checktype)dlsym(gge_handle, "luaL_checktype");
    if (!proxy_luaL_checktype && lua_handle) proxy_luaL_checktype = (PFN_luaL_checktype)dlsym(lua_handle, "luaL_checktype");
    if (!proxy_luaL_checktype) LOGE("Failed to resolve Lua symbol: luaL_checktype\n");
    proxy_luaL_checkany = (PFN_luaL_checkany)dlsym(handle, "luaL_checkany");
    if (!proxy_luaL_checkany && gge_handle) proxy_luaL_checkany = (PFN_luaL_checkany)dlsym(gge_handle, "luaL_checkany");
    if (!proxy_luaL_checkany && lua_handle) proxy_luaL_checkany = (PFN_luaL_checkany)dlsym(lua_handle, "luaL_checkany");
    if (!proxy_luaL_checkany) LOGE("Failed to resolve Lua symbol: luaL_checkany\n");
    proxy_luaL_newmetatable = (PFN_luaL_newmetatable)dlsym(handle, "luaL_newmetatable");
    if (!proxy_luaL_newmetatable && gge_handle) proxy_luaL_newmetatable = (PFN_luaL_newmetatable)dlsym(gge_handle, "luaL_newmetatable");
    if (!proxy_luaL_newmetatable && lua_handle) proxy_luaL_newmetatable = (PFN_luaL_newmetatable)dlsym(lua_handle, "luaL_newmetatable");
    if (!proxy_luaL_newmetatable) LOGE("Failed to resolve Lua symbol: luaL_newmetatable\n");
    proxy_luaL_setmetatable = (PFN_luaL_setmetatable)dlsym(handle, "luaL_setmetatable");
    if (!proxy_luaL_setmetatable && gge_handle) proxy_luaL_setmetatable = (PFN_luaL_setmetatable)dlsym(gge_handle, "luaL_setmetatable");
    if (!proxy_luaL_setmetatable && lua_handle) proxy_luaL_setmetatable = (PFN_luaL_setmetatable)dlsym(lua_handle, "luaL_setmetatable");
    if (!proxy_luaL_setmetatable) LOGE("Failed to resolve Lua symbol: luaL_setmetatable\n");
    proxy_luaL_testudata = (PFN_luaL_testudata)dlsym(handle, "luaL_testudata");
    if (!proxy_luaL_testudata && gge_handle) proxy_luaL_testudata = (PFN_luaL_testudata)dlsym(gge_handle, "luaL_testudata");
    if (!proxy_luaL_testudata && lua_handle) proxy_luaL_testudata = (PFN_luaL_testudata)dlsym(lua_handle, "luaL_testudata");
    if (!proxy_luaL_testudata) LOGE("Failed to resolve Lua symbol: luaL_testudata\n");
    proxy_luaL_checkudata = (PFN_luaL_checkudata)dlsym(handle, "luaL_checkudata");
    if (!proxy_luaL_checkudata && gge_handle) proxy_luaL_checkudata = (PFN_luaL_checkudata)dlsym(gge_handle, "luaL_checkudata");
    if (!proxy_luaL_checkudata && lua_handle) proxy_luaL_checkudata = (PFN_luaL_checkudata)dlsym(lua_handle, "luaL_checkudata");
    if (!proxy_luaL_checkudata) LOGE("Failed to resolve Lua symbol: luaL_checkudata\n");
    proxy_luaL_where = (PFN_luaL_where)dlsym(handle, "luaL_where");
    if (!proxy_luaL_where && gge_handle) proxy_luaL_where = (PFN_luaL_where)dlsym(gge_handle, "luaL_where");
    if (!proxy_luaL_where && lua_handle) proxy_luaL_where = (PFN_luaL_where)dlsym(lua_handle, "luaL_where");
    if (!proxy_luaL_where) LOGE("Failed to resolve Lua symbol: luaL_where\n");
    proxy_luaL_error = (PFN_luaL_error)dlsym(handle, "luaL_error");
    if (!proxy_luaL_error && gge_handle) proxy_luaL_error = (PFN_luaL_error)dlsym(gge_handle, "luaL_error");
    if (!proxy_luaL_error && lua_handle) proxy_luaL_error = (PFN_luaL_error)dlsym(lua_handle, "luaL_error");
    if (!proxy_luaL_error) LOGE("Failed to resolve Lua symbol: luaL_error\n");
    proxy_luaL_checkoption = (PFN_luaL_checkoption)dlsym(handle, "luaL_checkoption");
    if (!proxy_luaL_checkoption && gge_handle) proxy_luaL_checkoption = (PFN_luaL_checkoption)dlsym(gge_handle, "luaL_checkoption");
    if (!proxy_luaL_checkoption && lua_handle) proxy_luaL_checkoption = (PFN_luaL_checkoption)dlsym(lua_handle, "luaL_checkoption");
    if (!proxy_luaL_checkoption) LOGE("Failed to resolve Lua symbol: luaL_checkoption\n");
    proxy_luaL_fileresult = (PFN_luaL_fileresult)dlsym(handle, "luaL_fileresult");
    if (!proxy_luaL_fileresult && gge_handle) proxy_luaL_fileresult = (PFN_luaL_fileresult)dlsym(gge_handle, "luaL_fileresult");
    if (!proxy_luaL_fileresult && lua_handle) proxy_luaL_fileresult = (PFN_luaL_fileresult)dlsym(lua_handle, "luaL_fileresult");
    if (!proxy_luaL_fileresult) LOGE("Failed to resolve Lua symbol: luaL_fileresult\n");
    proxy_luaL_execresult = (PFN_luaL_execresult)dlsym(handle, "luaL_execresult");
    if (!proxy_luaL_execresult && gge_handle) proxy_luaL_execresult = (PFN_luaL_execresult)dlsym(gge_handle, "luaL_execresult");
    if (!proxy_luaL_execresult && lua_handle) proxy_luaL_execresult = (PFN_luaL_execresult)dlsym(lua_handle, "luaL_execresult");
    if (!proxy_luaL_execresult) LOGE("Failed to resolve Lua symbol: luaL_execresult\n");
    proxy_luaL_ref = (PFN_luaL_ref)dlsym(handle, "luaL_ref");
    if (!proxy_luaL_ref && gge_handle) proxy_luaL_ref = (PFN_luaL_ref)dlsym(gge_handle, "luaL_ref");
    if (!proxy_luaL_ref && lua_handle) proxy_luaL_ref = (PFN_luaL_ref)dlsym(lua_handle, "luaL_ref");
    if (!proxy_luaL_ref) LOGE("Failed to resolve Lua symbol: luaL_ref\n");
    proxy_luaL_unref = (PFN_luaL_unref)dlsym(handle, "luaL_unref");
    if (!proxy_luaL_unref && gge_handle) proxy_luaL_unref = (PFN_luaL_unref)dlsym(gge_handle, "luaL_unref");
    if (!proxy_luaL_unref && lua_handle) proxy_luaL_unref = (PFN_luaL_unref)dlsym(lua_handle, "luaL_unref");
    if (!proxy_luaL_unref) LOGE("Failed to resolve Lua symbol: luaL_unref\n");
    proxy_luaL_loadfilex = (PFN_luaL_loadfilex)dlsym(handle, "luaL_loadfilex");
    if (!proxy_luaL_loadfilex && gge_handle) proxy_luaL_loadfilex = (PFN_luaL_loadfilex)dlsym(gge_handle, "luaL_loadfilex");
    if (!proxy_luaL_loadfilex && lua_handle) proxy_luaL_loadfilex = (PFN_luaL_loadfilex)dlsym(lua_handle, "luaL_loadfilex");
    if (!proxy_luaL_loadfilex) LOGE("Failed to resolve Lua symbol: luaL_loadfilex\n");
    proxy_luaL_loadbufferx = (PFN_luaL_loadbufferx)dlsym(handle, "luaL_loadbufferx");
    if (!proxy_luaL_loadbufferx && gge_handle) proxy_luaL_loadbufferx = (PFN_luaL_loadbufferx)dlsym(gge_handle, "luaL_loadbufferx");
    if (!proxy_luaL_loadbufferx && lua_handle) proxy_luaL_loadbufferx = (PFN_luaL_loadbufferx)dlsym(lua_handle, "luaL_loadbufferx");
    if (!proxy_luaL_loadbufferx) LOGE("Failed to resolve Lua symbol: luaL_loadbufferx\n");
    proxy_luaL_loadstring = (PFN_luaL_loadstring)dlsym(handle, "luaL_loadstring");
    if (!proxy_luaL_loadstring && gge_handle) proxy_luaL_loadstring = (PFN_luaL_loadstring)dlsym(gge_handle, "luaL_loadstring");
    if (!proxy_luaL_loadstring && lua_handle) proxy_luaL_loadstring = (PFN_luaL_loadstring)dlsym(lua_handle, "luaL_loadstring");
    if (!proxy_luaL_loadstring) LOGE("Failed to resolve Lua symbol: luaL_loadstring\n");
    proxy_luaL_newstate = (PFN_luaL_newstate)dlsym(handle, "luaL_newstate");
    if (!proxy_luaL_newstate && gge_handle) proxy_luaL_newstate = (PFN_luaL_newstate)dlsym(gge_handle, "luaL_newstate");
    if (!proxy_luaL_newstate && lua_handle) proxy_luaL_newstate = (PFN_luaL_newstate)dlsym(lua_handle, "luaL_newstate");
    if (!proxy_luaL_newstate) LOGE("Failed to resolve Lua symbol: luaL_newstate\n");
    proxy_luaL_len = (PFN_luaL_len)dlsym(handle, "luaL_len");
    if (!proxy_luaL_len && gge_handle) proxy_luaL_len = (PFN_luaL_len)dlsym(gge_handle, "luaL_len");
    if (!proxy_luaL_len && lua_handle) proxy_luaL_len = (PFN_luaL_len)dlsym(lua_handle, "luaL_len");
    if (!proxy_luaL_len) LOGE("Failed to resolve Lua symbol: luaL_len\n");
    proxy_luaL_addgsub = (PFN_luaL_addgsub)dlsym(handle, "luaL_addgsub");
    if (!proxy_luaL_addgsub && gge_handle) proxy_luaL_addgsub = (PFN_luaL_addgsub)dlsym(gge_handle, "luaL_addgsub");
    if (!proxy_luaL_addgsub && lua_handle) proxy_luaL_addgsub = (PFN_luaL_addgsub)dlsym(lua_handle, "luaL_addgsub");
    if (!proxy_luaL_addgsub) LOGE("Failed to resolve Lua symbol: luaL_addgsub\n");
    proxy_luaL_gsub = (PFN_luaL_gsub)dlsym(handle, "luaL_gsub");
    if (!proxy_luaL_gsub && gge_handle) proxy_luaL_gsub = (PFN_luaL_gsub)dlsym(gge_handle, "luaL_gsub");
    if (!proxy_luaL_gsub && lua_handle) proxy_luaL_gsub = (PFN_luaL_gsub)dlsym(lua_handle, "luaL_gsub");
    if (!proxy_luaL_gsub) LOGE("Failed to resolve Lua symbol: luaL_gsub\n");
    proxy_luaL_setfuncs = (PFN_luaL_setfuncs)dlsym(handle, "luaL_setfuncs");
    if (!proxy_luaL_setfuncs && gge_handle) proxy_luaL_setfuncs = (PFN_luaL_setfuncs)dlsym(gge_handle, "luaL_setfuncs");
    if (!proxy_luaL_setfuncs && lua_handle) proxy_luaL_setfuncs = (PFN_luaL_setfuncs)dlsym(lua_handle, "luaL_setfuncs");
    if (!proxy_luaL_setfuncs) LOGE("Failed to resolve Lua symbol: luaL_setfuncs\n");
    proxy_luaL_getsubtable = (PFN_luaL_getsubtable)dlsym(handle, "luaL_getsubtable");
    if (!proxy_luaL_getsubtable && gge_handle) proxy_luaL_getsubtable = (PFN_luaL_getsubtable)dlsym(gge_handle, "luaL_getsubtable");
    if (!proxy_luaL_getsubtable && lua_handle) proxy_luaL_getsubtable = (PFN_luaL_getsubtable)dlsym(lua_handle, "luaL_getsubtable");
    if (!proxy_luaL_getsubtable) LOGE("Failed to resolve Lua symbol: luaL_getsubtable\n");
    proxy_luaL_traceback = (PFN_luaL_traceback)dlsym(handle, "luaL_traceback");
    if (!proxy_luaL_traceback && gge_handle) proxy_luaL_traceback = (PFN_luaL_traceback)dlsym(gge_handle, "luaL_traceback");
    if (!proxy_luaL_traceback && lua_handle) proxy_luaL_traceback = (PFN_luaL_traceback)dlsym(lua_handle, "luaL_traceback");
    if (!proxy_luaL_traceback) LOGE("Failed to resolve Lua symbol: luaL_traceback\n");
    proxy_luaL_requiref = (PFN_luaL_requiref)dlsym(handle, "luaL_requiref");
    if (!proxy_luaL_requiref && gge_handle) proxy_luaL_requiref = (PFN_luaL_requiref)dlsym(gge_handle, "luaL_requiref");
    if (!proxy_luaL_requiref && lua_handle) proxy_luaL_requiref = (PFN_luaL_requiref)dlsym(lua_handle, "luaL_requiref");
    if (!proxy_luaL_requiref) LOGE("Failed to resolve Lua symbol: luaL_requiref\n");
    proxy_luaL_buffinit = (PFN_luaL_buffinit)dlsym(handle, "luaL_buffinit");
    if (!proxy_luaL_buffinit && gge_handle) proxy_luaL_buffinit = (PFN_luaL_buffinit)dlsym(gge_handle, "luaL_buffinit");
    if (!proxy_luaL_buffinit && lua_handle) proxy_luaL_buffinit = (PFN_luaL_buffinit)dlsym(lua_handle, "luaL_buffinit");
    if (!proxy_luaL_buffinit) LOGE("Failed to resolve Lua symbol: luaL_buffinit\n");
    proxy_luaL_prepbuffsize = (PFN_luaL_prepbuffsize)dlsym(handle, "luaL_prepbuffsize");
    if (!proxy_luaL_prepbuffsize && gge_handle) proxy_luaL_prepbuffsize = (PFN_luaL_prepbuffsize)dlsym(gge_handle, "luaL_prepbuffsize");
    if (!proxy_luaL_prepbuffsize && lua_handle) proxy_luaL_prepbuffsize = (PFN_luaL_prepbuffsize)dlsym(lua_handle, "luaL_prepbuffsize");
    if (!proxy_luaL_prepbuffsize) LOGE("Failed to resolve Lua symbol: luaL_prepbuffsize\n");
    proxy_luaL_addlstring = (PFN_luaL_addlstring)dlsym(handle, "luaL_addlstring");
    if (!proxy_luaL_addlstring && gge_handle) proxy_luaL_addlstring = (PFN_luaL_addlstring)dlsym(gge_handle, "luaL_addlstring");
    if (!proxy_luaL_addlstring && lua_handle) proxy_luaL_addlstring = (PFN_luaL_addlstring)dlsym(lua_handle, "luaL_addlstring");
    if (!proxy_luaL_addlstring) LOGE("Failed to resolve Lua symbol: luaL_addlstring\n");
    proxy_luaL_addstring = (PFN_luaL_addstring)dlsym(handle, "luaL_addstring");
    if (!proxy_luaL_addstring && gge_handle) proxy_luaL_addstring = (PFN_luaL_addstring)dlsym(gge_handle, "luaL_addstring");
    if (!proxy_luaL_addstring && lua_handle) proxy_luaL_addstring = (PFN_luaL_addstring)dlsym(lua_handle, "luaL_addstring");
    if (!proxy_luaL_addstring) LOGE("Failed to resolve Lua symbol: luaL_addstring\n");
    proxy_luaL_addvalue = (PFN_luaL_addvalue)dlsym(handle, "luaL_addvalue");
    if (!proxy_luaL_addvalue && gge_handle) proxy_luaL_addvalue = (PFN_luaL_addvalue)dlsym(gge_handle, "luaL_addvalue");
    if (!proxy_luaL_addvalue && lua_handle) proxy_luaL_addvalue = (PFN_luaL_addvalue)dlsym(lua_handle, "luaL_addvalue");
    if (!proxy_luaL_addvalue) LOGE("Failed to resolve Lua symbol: luaL_addvalue\n");
    proxy_luaL_pushresult = (PFN_luaL_pushresult)dlsym(handle, "luaL_pushresult");
    if (!proxy_luaL_pushresult && gge_handle) proxy_luaL_pushresult = (PFN_luaL_pushresult)dlsym(gge_handle, "luaL_pushresult");
    if (!proxy_luaL_pushresult && lua_handle) proxy_luaL_pushresult = (PFN_luaL_pushresult)dlsym(lua_handle, "luaL_pushresult");
    if (!proxy_luaL_pushresult) LOGE("Failed to resolve Lua symbol: luaL_pushresult\n");
    proxy_luaL_pushresultsize = (PFN_luaL_pushresultsize)dlsym(handle, "luaL_pushresultsize");
    if (!proxy_luaL_pushresultsize && gge_handle) proxy_luaL_pushresultsize = (PFN_luaL_pushresultsize)dlsym(gge_handle, "luaL_pushresultsize");
    if (!proxy_luaL_pushresultsize && lua_handle) proxy_luaL_pushresultsize = (PFN_luaL_pushresultsize)dlsym(lua_handle, "luaL_pushresultsize");
    if (!proxy_luaL_pushresultsize) LOGE("Failed to resolve Lua symbol: luaL_pushresultsize\n");
    proxy_luaL_buffinitsize = (PFN_luaL_buffinitsize)dlsym(handle, "luaL_buffinitsize");
    if (!proxy_luaL_buffinitsize && gge_handle) proxy_luaL_buffinitsize = (PFN_luaL_buffinitsize)dlsym(gge_handle, "luaL_buffinitsize");
    if (!proxy_luaL_buffinitsize && lua_handle) proxy_luaL_buffinitsize = (PFN_luaL_buffinitsize)dlsym(lua_handle, "luaL_buffinitsize");
    if (!proxy_luaL_buffinitsize) LOGE("Failed to resolve Lua symbol: luaL_buffinitsize\n");
}

#endif // iOS/Android Proxy Guards
