LOCAL_PATH:= $(call my-dir)

include $(CLEAR_VARS)

DEPENDENT_LIB_PATH := $(LOCAL_PATH)/../../../../../dependent

SRC_PATH := $(DEPENDENT_LIB_PATH)/SQLite3MultipleCiphers

LOCAL_MODULE:= sqlite3mc

LOCAL_MODULE_FILENAME := sqlite3mc

LOCAL_SRC_FILES:= 	$(SRC_PATH)/src/sqlite3mc.c

LOCAL_CFLAGS += -D"HAVE_CIPHER_AES_128_CBC=0" -D"HAVE_CIPHER_AES_256_CBC=0" -D"HAVE_CIPHER_SQLCIPHER=0"


LOCAL_EXPORT_C_INCLUDES := $(LOCAL_PATH)

include $(BUILD_STATIC_LIBRARY)